version: '3'

services:
  sel_hub:
    image: selenium/hub:3.141.59-copernicium
    container_name: sel_hub
    privileged: true
    ports:
    - 4444:4444
    environment:
    - GRID_TIMEOUT=240
    - GRID_MAX_SESSION= 10
    - GRID_BROWSER_TIMEOUT=60
    networks:
    - selenium_grid

  nodechrome:
    image: selenium/node-chrome:3.141.59-copernicium
    privileged: true
    depends_on:
    - sel_hub
    ports:
    - 5900
    environment:
    - NODE_MAX_INSTANCES=10
    - NODE_MAX_SESSION=10
    - no_proxy=localhost
    - HUB_PORT_4444_TCP_ADDR=sel_hub
    - HUB_PORT_4444_TCP_PORT=4444
    networks:
    - selenium_grid

  nodefirefox:
    image: selenium/node-firefox:3.141.59-copernicium
    privileged: true
    depends_on:
    - sel_hub
    ports:
    - 5901
    environment:
    - NODE_MAX_INSTANCES=10
    - NODE_MAX_SESSION=10
    - no_proxy=localhost
    - HUB_PORT_4444_TCP_ADDR=sel_hub
    - HUB_PORT_4444_TCP_PORT=4444
    networks:
    - selenium_grid

networks:
  selenium_grid: